---

- name: "Check For Existing Script"
  uri:
    url: "http://{{ nexus_url }}/service/siesta/rest/v1/script/{{ item.script_name }}"
    method: GET
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    status_code: 200,404
  register: get_script_result
  retries: '{{ nexus_server_poll_retries }}'
  delay: '{{ nexus_server_poll_delay_in_seconds }}'
  until: get_script_result.status != 503

- name: "Delete Script if it Exists"
  uri:
    url: "http://{{ nexus_url }}/service/siesta/rest/v1/script/{{ item.script_name }}"
    method: DELETE
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    status_code: 204
  when: get_script_result.status == 200
  retries: '{{ nexus_server_poll_retries }}'
  delay: '{{ nexus_server_poll_delay_in_seconds }}'
  register: result
  until: result.status != 503

- name: "Create New Script"
  uri:
    url: "http://{{ nexus_url }}/service/siesta/rest/v1/script/"
    method: POST
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    body_format: json
    body: "{{ lookup('file', item.script_file )}}"
    force_basic_auth: yes
    status_code: 204
  retries: '{{ nexus_server_poll_retries }}'
  delay: '{{ nexus_server_poll_delay_in_seconds }}'
  register: result
  until: result.status != 503

- name: "Execute New Script"
  uri:
    url: "http://{{ nexus_url }}/service/siesta/rest/v1/script/{{ item.script_name }}/run"
    method: POST
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    headers:
      Content-Type: "text/plain"
    force_basic_auth: yes
    status_code: 200
  retries: '{{ nexus_server_poll_retries }}'
  delay: '{{ nexus_server_poll_delay_in_seconds }}'
  register: result
  until: result.status != 503
